### ISSUE TITLE
K2 compiler support

### ISSUE THREAD

**Issue by mvarnagiris** [arkivanov/Essenty#102]
With K2 compiler coming it would be good to make this library work with it too. Right now I'm getting this error:
```
Class SomeParcelableClass is not abstract and does not implement abstract member describeContents
```

K2 compiler enabled via `kotlin.experimental.tryK2=true` in `gradle.properties`

**Comment by arkivanov** [comment]
Thanks for raising! This issue is being tracked in: https://youtrack.jetbrains.com/issue/KT-58892.

**Comment by mvarnagiris** [comment]
Thanks for speedy response. I was not aware of that ticket. Feel free to close this 🙇

**Comment by arkivanov** [comment]
Seems like [KT-58892](https://youtrack.jetbrains.com/issue/KT-58892) has been postponed until Kotlin 2.0.

**Comment by arkivanov** [comment]
Unfortunately, KT-58892 has been closed as "As Designed", means we'll have to migrate to `kotlinx-serialization".

**Comment by mvarnagiris** [comment]
Oh interesting. So the whole Parcelable thing will be replaced with serialization then? Seems like a huge change. I guess this will also affect Decompose.

**Comment by arkivanov** [comment]
Yes. Basically, the following feature will not work in K2.

```kotlin
// commonMain

expect annotation class Parcelize
expect interface Parcelable
```

```kotlin
// androidMain

actual typealias Parcelize = kotlinx.parcelize.Parcelize
actual typealias Parcelable = android.os.Parcelable
```

The API will have to change, but fortunately it should look very similar to the current one. Plus, it will be fully multiplatform.

**Comment by arkivanov** [comment]
Ideally, we would need a stable Efficient Binary Format in `kotlinx-serialization`. Filed https://github.com/Kotlin/kotlinx.serialization/issues/2428.

**Comment by arkivanov** [comment]
Fixed in #115.

**Comment by arkivanov** [comment]
Released in `v1.3.0-alpha01`.

**Comment by hichamboushaba** [comment]
@arkivanov it seems Kotlin-parcelize was [updated](https://github.com/JetBrains/kotlin/commit/fa0d456850eb9348476fe110167aa27dcce595ec) to allow using it from the common code, are there any plans for restoring the support for Parcelable now?

I'm asking just to decide if I should start working on the migration to `@Serializable` or if I should postpone it.

**Comment by arkivanov** [comment]
Indeed, Parcelize can now be used from the common code. However, I really like how `kotlinx-serialization` works and supports all platforms. There are no plans to go back to Parcelize for now.
