### ISSUE TITLE
Following dependencies exported in the debugFramework binary are not specified as API-dependencies of a corresponding source set:

### ISSUE THREAD

**Issue by savan-ixfi** [arkivanov/Essenty#107]
<img width="1121" alt="image" src="https://github.com/arkivanov/Essenty/assets/131661149/242e48be-8b0f-43ea-8e44-96d0a4e052e7">
<img width="920" alt="image" src="https://github.com/arkivanov/Essenty/assets/131661149/fd7cef85-d37c-49f0-802a-f5bd82bc056e">
<img width="906" alt="image" src="https://github.com/arkivanov/Essenty/assets/131661149/7c69768c-e5b3-44f8-b091-789fcc948095">
<img width="910" alt="image" src="https://github.com/arkivanov/Essenty/assets/131661149/3df07ff8-f267-4fea-9262-8aedb0149c20">

**Comment by arkivanov** [comment]
As the error says, make sure you specify `com.arkivanov.essenty:lifecycle` dependency as `api`, not `implementation`. Also, please make sure you are using the same version of Essenty as used by Decompose. You can check the version of Essenty in the corresponding [Decompose release notes](https://github.com/arkivanov/Decompose/releases).

**Comment by arkivanov** [comment]
Closing this for now. Feel free to reopen if there are any issues.
