### ISSUE TITLE
Add UIViewController lifetime hooks

### ISSUE THREAD

**Issue by francismariano** [arkivanov/Essenty#110]
The version 1.5.10-beta01 of compose added UIViewController lifetime hooks (see https://github.com/JetBrains/compose-multiplatform-core/pull/779)

It is possible to do similar thing for essenty??

**Comment by arkivanov** [comment]
Yes, I think you can drive `LifecycleRegistry` using those callbacks.

**Comment by arkivanov** [comment]
You can use extension functions like `LifecycleRegistry#create`, `LifecycleRegistry#resume`, `LifecycleRegistry#stop` and `LifecycleRegistry#destroy`.

**Comment by arkivanov** [comment]
Closing this for now. Feel free to reopen if there are any issues.
