### ISSUE TITLE
Consider moving `decompose.extensions.compose.jetbrains.lifecycle.LifecycleController` to Essenty

### ISSUE THREAD

**Issue by Nek-12** [arkivanov/Essenty#160]
For desktop apps that don't need to use Decompose, but want to use Essenty for lifecycle handling, having LifecycleController in the Decompose introduces unnecessary overhead of depending on the whole library just for the lifecycle functionality. Consider moving functionality that allows to provide Essenty lifecycle for desktop, compose and other platforms to a separate module in Essenty instead of Decompose.

**Comment by arkivanov** [comment]
Thanks for the idea. Similarly to #158 this would require creating a separate module just for this API. For now I would like to avoid one-API modules, considering the simplicity of the API. I will keep this in mind as well.
