### ISSUE TITLE
StateKeeper fails to persist state on Android

### ISSUE THREAD

**Issue by hypergonial** [arkivanov/Essenty#184]
Hello,

Now I'm not entirely sure if this is due to me not knowing what I'm doing (quite probable) or a bug with persistence, but `StateKeeper` fails to actually save the state when the application is terminated on Android. I am unable to reproduce this on Desktop.

I've gone ahead and stripped down my project to the bare minimum for an easier repro, which you can find [here](https://github.com/hypergonial/statekeeper_bug_repro).

The relevant parts of that (as far as I can tell) are the following:

My root model:
```kotlin
interface RootComponent : BackHandlerOwner {
    val data: Value<Model>
    fun input(token: String)

    data class Model(
        val token: String? = null,
    )
}

class DefaultRootComponent(
    val ctx: ComponentContext,
) : RootComponent, ComponentContext by ctx {

    override val data = MutableValue(
        RootComponent.Model(
            token = stateKeeper.consume(key = "TOKEN", strategy = serializer<String>())
        )
    )

    init {
        stateKeeper.register(key = "TOKEN", strategy = serializer<String>()) {
            // This always gets printed, and yet, on Android, the token is not persisted.
            // On Desktop (JVM) the persistence works fine though.
            println("Looks like it is time to save the token, which is: ${data.value.token}")
            data.value.token
        }
    }

    override fun input(token: String) {
        data.value = data.value.copy(token = token)
    }
}
```

and my main activity:
```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        val root = DefaultRootComponent(defaultComponentContext())



        setContent {
            AppTheme {
                App(root)
            }
        }
    }
}
```

## Reproduction steps:
- Clone repo, open in Android Studio
- Launch the project with the "Android App" preset (I've tested this on my personal API33 device and an emulator running API35)
- Type anything into the textfield for the token
- Exit the app & close it fully so it is not running in the background
- Reopen the app

## Expected Result:
The text field's value is populated by the text from persistence by the statekeeper

## Actual Result:
The text field is empty

Trying the same thing with the "Desktop" launch preset works correctly.

---

Thanks in advance, and let me know if I should provide any additional info!

**Comment by hypergonial** [comment]
Hmm, upon some further testing, the wasmJS target also doesn't seem to work, but that is likely due to me not knowing how to configure the statekeeper for that platform.

**Comment by arkivanov** [comment]
On Android, `StateKeeper` works similarly to [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate), i.e. the state is only saved if the process is killed by the system due to memory pressure. The state is discarded if you kill the app manually. You can try the following to simulate process death: minimize the app and run `adb shell am kill <package_name>`, then the state should be restored if you open the app again via the shortcut.

As of `wasmJs`, `StateKeeper` requires some manual setup. You can hook it either to `sessionStorage` (persistent over page refreshes) or `localStorage` (persistent even if you close the tab and open the app again). I've got an example here: https://github.com/arkivanov/Minesweeper/blob/master/composeApp/src/wasmJsMain/kotlin/Main.kt#L23.

**Comment by hypergonial** [comment]
> On Android, `StateKeeper` works similarly to [SavedStateHandle](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate), i.e. the state is only saved if the process is killed by the system due to memory pressure. The state is discarded if you kill the app manually. You can try the following to simulate process death: minimize the app and run `adb shell am kill <package_name>`, then the state should be restored if you open the app again via the shortcut.
> 
> As of `wasmJs`, `StateKeeper` requires some manual setup. You can hook it either to `sessionStorage` (persistent over page refreshes) or `localStorage` (persistent even if you close the tab and open the app again). I've got an example here: https://github.com/arkivanov/Minesweeper/blob/master/composeApp/src/wasmJsMain/kotlin/Main.kt#L23.

Thanks for the quick reply! So I assume I shouldn't use `StateKeeper` to store client state/settings then, given this limitation of Android. Do you have any suggestions on what I should use instead?

P.S. Got WASM to work, thanks!

**Comment by arkivanov** [comment]
Yeah! For settings, you can try using [multiplatform-settings](https://github.com/russhwolf/multiplatform-settings) library. You can also check [SQLDelight](https://github.com/sqldelight/sqldelight) for database.

**Comment by hypergonial** [comment]
Looks promising, thanks for the very quick & concise replies! Closing now.
