### ISSUE TITLE
Utility function for StateKeeper

### ISSUE THREAD

**Issue by qwert2603** [arkivanov/Essenty#39]
Good day!

Extension function `InstanceKeeper.getOrCreate(...)` provides convenient way to get value from `InstanceKeeper` or create it otherwise.

It would be very useful to add similar function for `StateKeeper` to allow receive saved value from `StateKeeper` (if any) and at the same time register `supplier` that will provide value to save.

It will have the following benefits:
* `key` will be specified once only, less copy-paste typos
* it will ensure that `supplier` will provide value of the same type that is consumed from `StateKeeper` for the same `key`
* it will ensure that `supplier` is provided, so it will be harder to forget to register it

The function may be implemented as the following (name could be better):
```kotlin
inline fun <reified T : Parcelable> StateKeeper.registerAndConsume(key: String, noinline supplier: () -> T): T? {
    register(key, supplier)
    return consume(key)
}
```

And usage looks like:
```kotlin
class SomeValue : Parcelable

val someValue: SomeValue? = stateKeeper.registerAndConsume("some_key") { SomeValue() }
```

I can create PR, if needed.

**Comment by arkivanov** [comment]
Hello @qwert2603! As per my personal experience, there is nowhere to register a supplier at the time when when you consume the state.

```kotlin
class MyComponent {
    private val something = Something(stateKeeper.consume("key"))

    init {
        stateKeeper.register("key") { something.state } 
    }
}
```

Or this:

```kotlin
class MyComponent {
    private var state: State = stateKeeper.consume("key") ?: State()
 
    init {
        stateKeeper.register("key") { state }
    }
}
```

Could you please elaborate you use case? In the provided example, the supplier returns a new instance of `SomeValue`, not an existing state.

**Comment by qwert2603** [comment]
@arkivanov thanks for your answer!

Usually I prefer to separate "component's state" from "saved state", so only the needed data is saved in "saved state".
For example, `val isLoading: Boolean` shouldn't be in "saved state", because it doesn't make sense after the component's recreation.

So function `StateKeeper.consumeAndRegister` may be useful to create "component's state" from "saved state" and at the same time specify how to create "saved state" from "component's state":

```kotlin
data class ListState(
    val search: String,
    val isLoading: Boolean,
    val list: List<Any>?,
)

class ListComponent(
    componentContext: ComponentContext,
) : ComponentContext by componentContext {

    val state = MutableValue(createInitialValue())

    private fun createInitialValue(): ListState {
        val savedState = stateKeeper.consumeAndRegister("saved_state") {
            SavedState(search = state.value.search)
        }
        return ListState(
            search = savedState?.search.orEmpty(),
            isLoading = false,
            list = null,
        )
    }

    @Parcelize
    private class SavedState(val search: String) : Parcelable
}
```

And looks like `consumeAndRegister` is better name for this function.

**Comment by arkivanov** [comment]
Thanks for the use case provided!

You concern about clearing the state before saving is completely valid! You can either use a separate class, or just clear transient properties in the original state. Both options are valid. With the example provided by me it would look like this:

```kotlin
class MyComponent {
    private var state: State = stateKeeper.consume("key") ?: State()
 
    init {
        stateKeeper.register("key") { state.copy(isLoading = false) } // Clear transient properties before saving
    }
}
```

As of your use case, from my point of view you are abusing Kotlin's property initialisation order flaw. You are accessing the `state` property while it is being initialised. For better understanding, your code is equivalent to the following:

```kotlin
lateinit var state: State
state = stateKeeper.registerAndConsume("key") { state } ?: State()
```

So the code only compiles if the variable is `lateinit` or a separate function is used (like in your example). Do you still thing it is better than using two separate methods `consume` and `register` in this case?

**Comment by qwert2603** [comment]
@arkivanov thanks for pointing out the initialization order nuance. Though, there will not be errors, because `supplier` is not called in place, I agree that that previous implementation is not OK.

I think, that `consume` and `register` still may be combined together to get benefits those were listed in the initial message of this issue.

The following snippet illustrates some experiment, where initialization order is correct, but things are getting a bit complicated.
It is tied to `MutableValue` now, but implementation for other containers will be similar.

```kotlin
inline fun <T : Any, reified S : Parcelable> StateKeeperOwner.createMutableValue(
    savedStateKey: String,
    createInitialValue: (S?) -> T,
    noinline createSavedState: (T) -> S,
): MutableValue<T> {
    val savedState = stateKeeper.consume<S>(savedStateKey)
    val mutableValue = MutableValue(createInitialValue(savedState))
    stateKeeper.register(savedStateKey) { createSavedState(mutableValue.value) }
    return mutableValue
}

val state: MutableValue<ListState> = createMutableValue(
    savedStateKey = "saved_state",
    createInitialValue = { savedState ->
        ListState(
            search = savedState?.search.orEmpty(),
            isLoading = false,
            list = null,
        )
    },
    createSavedState = {
        SavedState(search = it.search)
    }
)
```

Do you think it is too specific to be added to the Essenty project?

**Comment by arkivanov** [comment]
@qwert2603 I think the `createMutableValue` is too specific, indeed. There many use cases of the `StateKeeper`, creating a `MutableValue` covers only one of them. It is also pretty simple, so easily can be just put in an end-user's project. As well as the initial `registerAndConsume`, which is "not OK".

I came up with the following more generic API, but I'm also not sure if it is a good one and worth adding to the library. It's all so simple, can be easily just copied to any project. What do you think?

```kotlin
inline fun <T, S : Parcelable> StateKeeper.register(
    key: String,
    clazz: KClass<out S>,
    noinline onSaveInstanceState: (T) -> S,
    instanceFactory: (savedState: S?) -> T
): T {
    val instance = instanceFactory(consume(key, clazz))
    register(key) { onSaveInstanceState(instance) }

    return instance
}

inline fun <T, reified S : Parcelable> StateKeeper.register(
    key: String,
    noinline onSaveInstanceState: (T) -> S,
    instanceFactory: (savedState: S?) -> T
): T =
    register(
        key = key,
        clazz = S::class,
        onSaveInstanceState = onSaveInstanceState,
        instanceFactory = instanceFactory,
    )
```

**Comment by qwert2603** [comment]
@arkivanov I think such generic function from your snippet can be added to the library to show the approach. While more specific functions for `MutableValue` and other containers can be placed in end-user's project. So the library will not push to usage some of them.

**Comment by arkivanov** [comment]
@qwert2603 thanks for your opinions, however I am still not convinced to add this API. It is very simple, and can be easily added manually to a project. I think I will close this issue untill there are more use cases or requests. Thanks anyway!

**Comment by qwert2603** [comment]
@arkivanov I understand. Thanks for explanations and for this project!
