### ISSUE TITLE
Support optional values in StateKeeper's supplier

### ISSUE THREAD

**Issue by vganin** [arkivanov/Essenty#66]
`StateKeeper` makes a bit redundantly strong contract for supplier imo, requiring non-optional `Parcelable` from supplier ([here](https://github.com/arkivanov/Essenty/blob/4922dfbb952ccc1d344b7b43b7d40d44da1eac44/state-keeper/src/commonMain/kotlin/com/arkivanov/essenty/statekeeper/StateKeeper.kt#L10)).

Simply put, we have
```kotlin
interface StateKeeper {
    ...
    fun <T : Parcelable> register(key: String, supplier: () -> T)
    ...
}
```
And I want
```kotlin
interface StateKeeper {
    ...
    fun <T : Parcelable?> register(key: String, supplier: () -> T)
    ...
}
```
Note the `T : Parcelable?` part.

Maybe I'm not seeing the reason behind the non-nullable contract, please correct me if I'm wrong.

**Comment by arkivanov** [comment]
Yeah, I think this is doable. It could be `fun <T : Parcelable> register(key: String, supplier: () -> T?)`. I will try implementing it.
